# Generated by Django 5.0 on 2023-12-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flase_app', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='defaultUser', max_length=128),
        ),
    ]
