# Generated by Django 4.2.9 on 2024-02-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flase_app', '0012_gas_amount_gas_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gas',
            name='amount',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Reader'), (1, 'Editor'), (2, 'Operator'), (3, 'Administrator')], default=0),
        ),
    ]
