# Generated by Django 4.2.10 on 2024-02-11 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flase_app", "0013_remove_gas_amount_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="gas",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["workplace__building__name", "workplace__name", "name"]
            },
        ),
        migrations.AlterModelOptions(
            name="owner",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="workplace",
            options={"ordering": ["building__name", "name"]},
        ),
        migrations.RemoveField(
            model_name="cylinderchange",
            name="note",
        ),
        migrations.RemoveField(
            model_name="gas",
            name="note",
        ),
    ]
