# Generated by Django 4.2.10 on 2024-02-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flase_app", "0014_alter_building_options_alter_gas_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cylinderlife",
            name="pressure_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
