# Generated by Django 4.2.10 on 2024-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flase_app', '0015_cylinderlife_pressure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderlife',
            name='manometer_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cylinderlife',
            name='manometer_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
