# Generated by Django 4.2.10 on 2024-03-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flase_app', '0017_cylinderlife_is_latest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gas',
            options={'ordering': ['name', 'purity']},
        ),
        migrations.AddField(
            model_name='gas',
            name='purity',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='gas',
            constraint=models.UniqueConstraint(models.F('name'), models.F('purity'), name='gas__name_purity__unique'),
        ),
    ]
