# Generated by Django 4.2.10 on 2024-03-25 22:51

from django.db import migrations, models


def insert_alert(apps, schema_editor):
    Alert = apps.get_model("flase_app", "Alert")
    Alert.objects.create(pk=1, pressure_below=None)


def delete_alert(apps, schema_editor):
    Alert = apps.get_model("flase_app", "Alert")
    Alert.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("flase_app", "0018_alter_gas_options_gas_purity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pressure_below", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(insert_alert, delete_alert),
    ]
